// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub fee_payer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="3")]
    pub signers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="4")]
    pub fee: u64,
    #[prost(uint64, tag="5")]
    pub compute_units_consumed: u64,
    #[prost(message, repeated, tag="6")]
    pub swaps: ::prost::alloc::vec::Vec<Swap>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swap {
    #[prost(enumeration="Protocol", tag="1")]
    pub protocol: i32,
    #[prost(bytes="vec", tag="2")]
    pub program_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="3")]
    pub stack_height: u32,
    #[prost(bytes="vec", tag="4")]
    pub amm: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub amm_pool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub input_mint: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="8")]
    pub input_amount: u64,
    #[prost(bytes="vec", tag="9")]
    pub output_mint: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="10")]
    pub output_amount: u64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Protocol {
    Unspecified = 0,
    Boop = 1,
    Darklake = 2,
    Dumpfun = 3,
    JupiterV4 = 4,
    JupiterV6 = 5,
    MeteoraDaam = 6,
    MeteoraDlmm = 7,
    OrcaWhirlpool = 8,
    Pumpfun = 9,
    PumpfunAmm = 10,
    RaydiumAmmV4 = 11,
    RaydiumClmm = 12,
    RaydiumCpmm = 13,
    RaydiumLaunchpad = 14,
    MeteoraAmm = 15,
    Byreal = 16,
    Moonshot = 17,
    Pancakeswap = 18,
}
impl Protocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Protocol::Unspecified => "PROTOCOL_UNSPECIFIED",
            Protocol::Boop => "PROTOCOL_BOOP",
            Protocol::Darklake => "PROTOCOL_DARKLAKE",
            Protocol::Dumpfun => "PROTOCOL_DUMPFUN",
            Protocol::JupiterV4 => "PROTOCOL_JUPITER_V4",
            Protocol::JupiterV6 => "PROTOCOL_JUPITER_V6",
            Protocol::MeteoraDaam => "PROTOCOL_METEORA_DAAM",
            Protocol::MeteoraDlmm => "PROTOCOL_METEORA_DLMM",
            Protocol::OrcaWhirlpool => "PROTOCOL_ORCA_WHIRLPOOL",
            Protocol::Pumpfun => "PROTOCOL_PUMPFUN",
            Protocol::PumpfunAmm => "PROTOCOL_PUMPFUN_AMM",
            Protocol::RaydiumAmmV4 => "PROTOCOL_RAYDIUM_AMM_V4",
            Protocol::RaydiumClmm => "PROTOCOL_RAYDIUM_CLMM",
            Protocol::RaydiumCpmm => "PROTOCOL_RAYDIUM_CPMM",
            Protocol::RaydiumLaunchpad => "PROTOCOL_RAYDIUM_LAUNCHPAD",
            Protocol::MeteoraAmm => "PROTOCOL_METEORA_AMM",
            Protocol::Byreal => "PROTOCOL_BYREAL",
            Protocol::Moonshot => "PROTOCOL_MOONSHOT",
            Protocol::Pancakeswap => "PROTOCOL_PANCAKESWAP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROTOCOL_UNSPECIFIED" => Some(Self::Unspecified),
            "PROTOCOL_BOOP" => Some(Self::Boop),
            "PROTOCOL_DARKLAKE" => Some(Self::Darklake),
            "PROTOCOL_DUMPFUN" => Some(Self::Dumpfun),
            "PROTOCOL_JUPITER_V4" => Some(Self::JupiterV4),
            "PROTOCOL_JUPITER_V6" => Some(Self::JupiterV6),
            "PROTOCOL_METEORA_DAAM" => Some(Self::MeteoraDaam),
            "PROTOCOL_METEORA_DLMM" => Some(Self::MeteoraDlmm),
            "PROTOCOL_ORCA_WHIRLPOOL" => Some(Self::OrcaWhirlpool),
            "PROTOCOL_PUMPFUN" => Some(Self::Pumpfun),
            "PROTOCOL_PUMPFUN_AMM" => Some(Self::PumpfunAmm),
            "PROTOCOL_RAYDIUM_AMM_V4" => Some(Self::RaydiumAmmV4),
            "PROTOCOL_RAYDIUM_CLMM" => Some(Self::RaydiumClmm),
            "PROTOCOL_RAYDIUM_CPMM" => Some(Self::RaydiumCpmm),
            "PROTOCOL_RAYDIUM_LAUNCHPAD" => Some(Self::RaydiumLaunchpad),
            "PROTOCOL_METEORA_AMM" => Some(Self::MeteoraAmm),
            "PROTOCOL_BYREAL" => Some(Self::Byreal),
            "PROTOCOL_MOONSHOT" => Some(Self::Moonshot),
            "PROTOCOL_PANCAKESWAP" => Some(Self::Pancakeswap),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
